--- 
before_script: 
  - "sh -c \"if [ '$DB' = 'mysql' ]; then mysql -e 'drop database if exists parm_namespaced_tests; create database parm_namespaced_tests;'; fi\""
  - "sh -c \"if [ '$DB' = 'mysql' ]; then mysql parm_namespaced_tests < tests/data/namespaced-test-data.sql; fi\""
  - "sh -c \"if [ '$DB' = 'mysql' ]; then mysql -e 'drop database if exists \\`parm-global-tests\\`; create database \\`parm-global-tests\\`;'; fi\""
  - "sh -c \"if [ '$DB' = 'mysql' ]; then mysql parm-global-tests < tests/data/global-test-data.sql; fi\""
  - "composer install --prefer-source --dev"
env: 
  - DB=mysql
language: php
php: 
  - 5.4
  - 5.5
  - 5.6
script: ./vendor/bin/phpunit
